import path from "node:path";
import { fileURLToPath } from "node:url";

import { storybookTest } from "@storybook/addon-vitest/vitest-plugin";
import { playwright } from "@vitest/browser-playwright";
import { defineConfig } from "vitest/config";

const dirname = path.dirname(fileURLToPath(import.meta.url));

// Test runner for the web half of the product (`mobile/` has its own toolchain
// and is excluded everywhere here). Two projects:
//
//   unit      — pure logic in node. Fast, no DOM, no network. This is where
//               `lib/` lives and where most tests belong.
//   storybook — every story in the UI Lab is also a test: it must render in a
//               real browser (Playwright/chromium) without throwing and its
//               play function must pass. The gallery IS the suite.
//
// Coverage feeds two gates in CI (.github/workflows/ci.yml):
//   1. the ratchet — thresholds below may only ever go UP (see CLAUDE.md);
//   2. diff-cover — lines CHANGED by a PR must be ≥85% covered, which is the
//      gate that actually bites. Cobertura output exists for it.
export default defineConfig({
  // `@/…` imports resolve from tsconfig paths — Vite reads them natively.
  resolve: { tsconfigPaths: true },
  test: {
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "lcov", "cobertura"],
      reportsDirectory: "coverage",

      // Everything that ships to users is measured, tested or not — a coverage
      // number computed only over files that happen to have tests flatters
      // itself and makes the ratchet meaningless.
      //
      // Source extensions only: `app/` also holds css, fonts and images, and
      // the v8 provider tries to parse whatever it is handed.
      include: [
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
        "db/**/*.ts",
        "lib/**/*.{ts,tsx}",
        "proxy.ts",
      ],

      exclude: [
        // Not application code.
        "**/*.d.ts",
        "**/*.test.{ts,tsx}",
        // Stories are the bench, not shipped behaviour: they are the
        // instrument that measures components, so measuring them too would be
        // circular.
        "**/*.stories.tsx",
        // Generated by Drizzle from the schema — never hand-edited, so a test
        // over it would assert the generator, not our behaviour.
        "drizzle/**",
        // One-shot operational scripts (promote-to-admin, stripe-setup,
        // seeds). They talk to live vendors by design; a unit test around them
        // would be theatre. Run manually, verified by their own output.
        "scripts/**",
        // The Expo app: separate project, separate toolchain, separate lint.
        "mobile/**",
        // Loose design references, not part of any bundle.
        "design_handoff_matio_redesign/**",
      ],

      // RATCHET — these numbers move in one direction only. Raised coverage in
      // a PR? Raise the floor in the SAME PR. Lowering one is a review blocker.
      //
      // История движения: 1.10 (нулевой старт, этап 03) → 1.37 (истории Lab
      // исполняют компоненты, этап 04) → 1.45 (тесты /api/healthz, этап 05) →
      // 3.80 (замок стенда, #62: proxy.ts впервые исполняется тестами и тянет
      // за собой пол-`lib/`) → 4.97 (наблюдаемость, #36: lib/observability.ts,
      // /api/readyz и тест-аудит логов — оба новых файла покрыты на 100%).
      // Полы идут следом, округлением вниз.
      // → 6.5 (редизайн /about + /press, #88: контент-компоненты исполняются
      //   историями, ростер и SEO-хелперы — юнитами) → 8.3 (#17: surface
      //   /api/v1 для мобильного — 48 тестов на четыре роута и общий слой).
      thresholds: {
        lines: 14.0,
        functions: 12.3,
        branches: 10.6,
        statements: 13.8,
      },
    },

    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          environment: "node",
          include: [
            // `infra/` — скрипты эксплуатации (бэкапы). В покрытие они не
            // входят (см. include выше), но чистые правила вроде ретеншена
            // удаляют объекты хранилища, и проверять их обязательно.
            "{app,components,db,infra,lib,tools}/**/*.{test,spec}.{ts,tsx}",
            "proxy.test.ts",
          ],
        },
      },
      {
        extends: true,
        plugins: [
          storybookTest({ configDir: path.join(dirname, ".storybook") }),
        ],
        test: {
          name: "storybook",
          browser: {
            enabled: true,
            headless: true,
            provider: playwright({}),
            instances: [{ browser: "chromium" }],
            expect: {
              toMatchScreenshot: {
                // Подобрано опытом, а не на глаз: при 2% перекрашенная
                // кнопка на широком холсте НЕ ловилась — её пиксели не
                // набирали порога (доска из шести кнопок прошла зелёной с
                // одной бордовой). 0.1% ловит обе доски и переживает шум
                // сглаживания.
                comparatorName: "pixelmatch",
                comparatorOptions: { allowedMismatchedPixelRatio: 0.001 },
              },
            },
          },
        },
      },
    ],
  },
});
