import { defineConfig } from "vitest/config";

// Test runner for the web half of the product (`mobile/` has its own toolchain
// and is excluded everywhere here).
//
// Environment is `node` by default — most of what is worth testing in this repo
// is pure logic in `lib/` that needs neither a DOM nor a network. A component
// test opts into jsdom per file with a docblock:
//
//   /** @vitest-environment jsdom */
//
// Coverage feeds two gates that live in CI (.github/workflows/ci.yml):
//   1. the ratchet — thresholds below may only ever go UP (see CLAUDE.md);
//   2. diff-cover — lines CHANGED by a PR must be ≥85% covered, which is the
//      gate that actually bites. Cobertura output exists for it.
export default defineConfig({
  // `@/…` imports resolve from tsconfig paths — Vite reads them natively.
  resolve: { tsconfigPaths: true },
  test: {
    environment: "node",
    include: [
      "{app,components,db,lib,tools}/**/*.{test,spec}.{ts,tsx}",
      "proxy.test.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "lcov", "cobertura"],
      reportsDirectory: "coverage",

      // Everything that ships to users is measured, tested or not — a coverage
      // number computed only over files that happen to have tests flatters
      // itself and makes the ratchet meaningless.
      // Source extensions only: `app/` also holds css, fonts and images, and
      // the v8 provider tries to parse whatever it is handed.
      include: [
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
        "db/**/*.ts",
        "lib/**/*.{ts,tsx}",
        "proxy.ts",
      ],

      exclude: [
        // Not application code.
        "**/*.d.ts",
        "**/*.test.{ts,tsx}",
        // Generated by Drizzle from the schema — never hand-edited, so a test
        // over it would assert the generator, not our behaviour.
        "drizzle/**",
        // One-shot operational scripts (promote-to-admin, stripe-setup,
        // seeds). They talk to live vendors by design; a unit test around them
        // would be theatre. Run manually, verified by their own output.
        "scripts/**",
        // The Expo app: separate project, separate toolchain, separate lint.
        "mobile/**",
        // Loose design references, not part of any bundle.
        "design_handoff_matio_redesign/**",
      ],

      // RATCHET — these numbers move in one direction only. Raised coverage in
      // a PR? Raise the floor in the SAME PR. Lowering one is a review blocker.
      // Стартовые значения — честное измерение на 31.07.2026, округлённое вниз
      // (было: statements 1.10, branches 1.21, functions 0.65, lines 1.04).
      // Проект начинал без единого теста, поэтому цифры такие; смысл порога не
      // в величине, а в направлении.
      thresholds: {
        lines: 1,
        functions: 0.6,
        branches: 1,
        statements: 1,
      },
    },
  },
});
