import path from "node:path";
import { fileURLToPath } from "node:url";

import { storybookTest } from "@storybook/addon-vitest/vitest-plugin";
import { playwright } from "@vitest/browser-playwright";
import { defineConfig } from "vitest/config";

const dirname = path.dirname(fileURLToPath(import.meta.url));

// Test runner for the product. Three projects:
//
//   unit      — pure logic in node. Fast, no DOM, no network. This is where
//               `lib/` lives and where most tests belong.
//   mobile    — the Expo app's component tests, in node on react-native-web
//               (see the project below). `mobile/` keeps its own toolchain and
//               stays out of coverage; only its tests run here.
//   storybook — every story in the UI Lab is also a test: it must render in a
//               real browser (Playwright/chromium) without throwing and its
//               play function must pass. The gallery IS the suite.
//
// Coverage feeds two gates in CI (.github/workflows/ci.yml):
//   1. the ratchet — thresholds below may only ever go UP (see CLAUDE.md);
//   2. diff-cover — lines CHANGED by a PR must be ≥85% covered, which is the
//      gate that actually bites. Cobertura output exists for it.
export default defineConfig({
  // `@/…` imports resolve from tsconfig paths — Vite reads them natively.
  resolve: { tsconfigPaths: true },
  test: {
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "lcov", "cobertura"],
      reportsDirectory: "coverage",

      // Everything that ships to users is measured, tested or not — a coverage
      // number computed only over files that happen to have tests flatters
      // itself and makes the ratchet meaningless.
      //
      // Source extensions only: `app/` also holds css, fonts and images, and
      // the v8 provider tries to parse whatever it is handed.
      include: [
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
        "db/**/*.ts",
        "lib/**/*.{ts,tsx}",
        "proxy.ts",
      ],

      exclude: [
        // Not application code.
        "**/*.d.ts",
        "**/*.test.{ts,tsx}",
        // Stories are the bench, not shipped behaviour: they are the
        // instrument that measures components, so measuring them too would be
        // circular.
        "**/*.stories.tsx",
        // Generated by Drizzle from the schema — never hand-edited, so a test
        // over it would assert the generator, not our behaviour.
        "drizzle/**",
        // One-shot operational scripts (promote-to-admin, stripe-setup,
        // seeds). They talk to live vendors by design; a unit test around them
        // would be theatre. Run manually, verified by their own output.
        "scripts/**",
        // The Expo app: separate project, separate toolchain, separate lint.
        "mobile/**",
        // Loose design references, not part of any bundle.
        "design_handoff_matio_redesign/**",
      ],

      // RATCHET — these numbers move in one direction only. Raised coverage in
      // a PR? Raise the floor in the SAME PR. Lowering one is a review blocker.
      //
      // История движения: 1.10 (нулевой старт, этап 03) → 1.37 (истории Lab
      // исполняют компоненты, этап 04) → 1.45 (тесты /api/healthz, этап 05) →
      // 3.80 (замок стенда, #62: proxy.ts впервые исполняется тестами и тянет
      // за собой пол-`lib/`) → 4.97 (наблюдаемость, #36: lib/observability.ts,
      // /api/readyz и тест-аудит логов — оба новых файла покрыты на 100%).
      // Полы идут следом, округлением вниз.
      // → 6.5 (редизайн /about + /press, #88: контент-компоненты исполняются
      //   историями, ростер и SEO-хелперы — юнитами) → 8.3 (#17: surface
      //   /api/v1 для мобильного — 48 тестов на четыре роута и общий слой)
      // → 20.8 (#127: плеер /watch впервые исполняется jsdom-тестом —
      //   две тысячи строк player.tsx вошли в измерение; 20.90/20.46/16.85/16.37
      //   по прогону, полы с запасом 0.1 на дрейф между macOS и CI)
      // → 21.6 (#128: хиро-плеер — фатальные/нефатальные ошибки и перевыпуск
      //   токена тизера; lib/hero-preview.ts + /api/hero-preview-token покрыты
      //   на 100%; 21.74/21.25/17.34/17.15 по прогону, те же 0.1 запаса).
      // → 24.1 (#31: токены теней/градиентов — листы Shadows/Gradients и
      //   история Icon исполняют lib/design.ts и icon.tsx целиком;
      //   24.28/24.00/19.22/19.96 по прогону, те же 0.1 запаса).
      // → 28.8 (#143: ветвящееся видео — lib/branching.ts (правила графа),
      //   экшены развилки и publish-guard, панель fork-panel в jsdom,
      //   continue-watching через ветку, WHERE-исключения /api/v1, паритет
      //   секции fork админ-словаря; после ревью — deleteSeason в
      //   транзакции, вебхук Mux и рассылка впервые под тестами;
      //   28.92/24.84/23.40/28.72 по прогону поверх свежего main (#31
      //   влит), те же 0.1 запаса).
      // → 32.0 (#162: ретеншен — lib/retention.ts и /api/cron/retention
      //   покрыты целиком, кейс лог-аудита, открытый путь крона в замке
      //   стенда; 32.79/27.18/27.25/32.45 по прогону поверх свежего main
      //   (d11db144, #183 влит). Полы по правилу «max(main, локальный − 0.7)»:
      //   локальный замер завышает против CI на ~0.5–0.7 п.п. — окончательные
      //   числа выставляются по логу CI).
      // → 35.2 (#144: плеер ветвления — правила кандидатов/нумерации в
      //   lib/branching.ts, восемь jsdom-сценариев развилки в player.test.tsx
      //   (промпт, выбор, таймаут, тихая реконвергенция, концовка, Lead,
      //   список, удержание refresh-remount), оверлей выбора и пять
      //   Lab-вариантов исполняются историями, рельс продолжения через
      //   незавершённую ветку; 35.97/30.28/30.51/35.71 по прогону поверх
      //   свежего main (#162 влит), то же правило «max(main, локальный −
      //   0.7)»).
      // → 38.6/31.7/33.2/38.1 (#198: тир эпизода решает под гейтом
      //   регистрации — resolveEffectiveTier/resolveRequestTier/isFreeToWatch
      //   таблицей, первые тесты веб-маршрута токена (14 кейсов: кому минтим,
      //   кому 403 и с какой причиной), tier-гейт анонимного флаша в ядре
      //   сегментов. Числа по логу CI прогона ветки).
      // → 38.7/31.7/33.2/38.3 (#202: источник адреса возврата после оплаты —
      //   чистая функция вместо запасного localhost, таблица на все ветки
      //   включая отказ в развёрнутом окружении).
      // → 41.1/33.2/34.9/40.6 (#210: кошелёк на paywall. Впервые под тестами
      //   оба серверных билдера чекаута: resolveWalletGate таблицей на все
      //   шесть отказов, тридцать кейсов на createAuthWalletCheckoutSession
      //   (каждый отказ доказан МОЛЧАНИЕМ в сторону Stripe) и на
      //   createAuthCheckoutSession как регрессионная защита рефакторинга
      //   prepareAuthCheckout, диспетчер, пятнадцать jsdom-сценариев кнопки,
      //   паритет двух поверхностей, метаданные отказа от 14-дневного права,
      //   подстановка id сессии, открытый префикс /.well-known, пять
      //   Lab-вариантов. Локальный прогон 41.82/33.99/35.68/41.37 поверх
      //   свежего main (bc0ac73c); полы по правилу «max(main, локальный −
      //   0.7)» — прошлый прогон CI отставал от локального на 0.4–0.65 п.п.).
      // → 41.2/33.3/35.0/40.7 (#214: правки по ревью кошелька — согласие с
      //   Условиями в jsdom-тестах кнопки, запись без метки времени, два кейса
      //   аудита логов на путях чекаута. Попутно найдено и исправлено: частичные
      //   моки аудита подменяли sendCapiEvents для ВСЕГО файла, и кейсы
      //   зеркала Stripe перестали исполнять lib/meta-capi.ts (3% вместо
      //   90.9%) — теперь моки по умолчанию делегируют реальному коду.
      //   Локально 41.93/34.06/35.74/41.48 поверх d851db7a; полы по правилу
      //   «max(main, локальный − 0.7)»).
      // → 41.3/33.6/35.3/40.8 (#214, второй круг ревью: кейс аудита логов
      //   через createAuthCheckoutSession впервые исполняет prepareAuthCheckout
      //   в аудите — строка 191 теперь покрыта; кейс ошибки подписи Clerk.
      //   Числа по ЛОГУ CI прогона 34507683810: 41.40/33.70/35.43/40.97 —
      //   полы на 0.1 ниже, как в истории выше. Локальный 42.14 по строкам
      //   разошёлся с CI на 0.74 п.п. — больше запаса 0.7 из правила
      //   «локальный − 0.7», и первая версия пола (41.4) легла ровно на
      //   число CI, без запаса на дрейф).
      // → 41.7/33.7/35.4/41.2 (#195: остатки throw в админских формах —
      //   createSeason и deleteEpisode со страницы сезона отвечают кодами
      //   (season_number_invalid / season_number_taken /
      //   episode_is_choice_target), общий read isChoiceTarget в
      //   lib/branching-db.ts под тестами через экшен, редирект после
      //   удаления доказан броском NEXT_REDIRECT. Локально
      //   42.46/34.41/36.17/41.96 поверх f390a8c2; полы по правилу
      //   «max(main, локальный − 0.7)» — окончательные числа по логу CI).
      // → 42.3/34.3/36.4/41.8 (#180: стирание у процессоров, часть 2 —
      //   lib/erase-user.ts (ядро стирания с внедрёнными зависимостями,
      //   dry-run, парсер, сводки) и lib/posthog-erase.ts (lookup → delete,
      //   все пять статусов) покрыты целиком, три кейса вебхука × PostHog,
      //   два кейса лог-аудита. Числа по ЛОГУ CI прогона 34929564909:
      //   42.37/34.47/36.62/41.87 — полы на 0.1 ниже. Локальный замер
      //   43.17/35.04/37.12/42.63 завысил на 0.8 п.п. по строкам — больше
      //   запаса 0.7 из правила «локальный − 0.7», первая версия полов
      //   (42.4/…/41.9) легла ВЫШЕ чисел CI и уронила прогон; отсюда
      //   правило: финал только по логу CI).
      // → 43.0/35.0/37.1/42.5 (#217: stateful-фейк Stripe в
      //   app/subscribe/wallet-actions.test.ts исполняет sweep-ветки
      //   createSoleOpenSession, новый app/checkout/checkout-client.test.tsx
      //   впервые покрывает клиент /checkout, проба checkoutSessionState с
      //   привязкой к покупателю и кейс аудита логов. Числа по ЛОГУ CI
      //   прогона 34930482872 на слитом дереве (origin/main 75bfe777 +
      //   #217): 43.09/35.12/37.22/42.59 — полы на 0.1 ниже, как в правиле
      //   выше. Локальный замер 43.06/35.03/36.58/42.56 на предыдущем
      //   слиянии для справки; финал только по логу CI).
      // → 43.2/35.3/37.3/42.7 (#223: стирание тумбстоунит ВСЕХ клиентов
      //   Stripe по адресу — customers.search в lib/erase-user.ts (поиск,
      //   экранирование, три статуса, has_more, dry-run, сводки, шаг «руками»)
      //   под семью кейсами ядра + кейс вебхука + три кейса лог-аудита.
      //   Числа по ЛОГУ CI прогона 34931903175 на слитом дереве (origin/main
      //   759ea96f + #223): 43.31/35.39/37.45/42.79 — полы на 0.1 ниже.
      //   Локальный замер 44.11/35.95/37.95/43.53 завысил по строкам на
      //   0.8 п.п. — как в #180: первая версия полов (43.4/…/42.8) легла
      //   ВЫШЕ чисел CI по строкам и выражениям и уронила прогон; финал
      //   только по логу CI).
      // → 44.6/35.8/38.7/44.0 (#224: гостевой pay-first чекаут впервые под
      //   тестами — app/subscribe/guest-actions.ts целиком (23 кейса на
      //   общем stateful-фейке Stripe tools/test/stripe-checkout-fake.ts,
      //   вынесенном из wallet-actions.test.ts), lib/guest-checkout-sessions.ts
      //   (один upsert RETURNING old.session_id, пришпилен текстом SQL через
      //   pg-proxy, самопрунинг), expireIfOpen в lib/checkout-session.ts,
      //   откат клейма после неудачного истечения, четыре кейса лог-аудита.
      //   Числа по ЛОГУ CI прогона 34934053912 на слитом дереве (origin/main
      //   ba7d3a39, #223 влит + #224): 44.71/35.92/38.82/44.13 — полы на
      //   0.1 ниже, как в правиле выше. Локальный замер того же дерева
      //   45.50/36.48/39.29/44.87 завысил на 0.8 п.п. по строкам — первая
      //   версия полов (44.4/…, по локальному замеру до слияния) легла
      //   ВЫШЕ числа CI и уронила прогон; финал только по логу CI).
      // → 44.8/35.9/38.8/44.2 (#227: лимит на частоту создания Checkout
      //   Session у авторизованного — lib/checkout-rate-limit.ts обобщён
      //   (checkoutRateLimited(key, limit)) и впервые под тестами целиком
      //   (окно по часу, счёт на каждый вызов, fail-open, прунинг, env-рычаги),
      //   семь кейсов #227 в wallet-actions.test.ts на реальном лимитере,
      //   кейс лог-аудита. Локальный замер на origin/main f40d7795 + #227:
      //   45.73/36.60/39.45/45.09 (завысил на ~0.8 п.п.); CI на 7431e721
      //   (прогон 34935817391): 44.94/36.04/38.99/44.34 — полы на 0.1 ниже,
      //   выставлены основной сессией по логу CI).
      // → 45.0/36.2/39.0/44.4 (#245: нативный шелл мобильного — единственный
      //   новый код в измерении это чистый lib/catalog-filters.ts (чипы
      //   жанров + поиск Browse, 14 кейсов, покрыт целиком) и новые секции
      //   app-dictionaries.ts под тестом паритета. Числа по ЛОГУ CI прогона
      //   35380760456 на ветке: 45.12/36.30/39.15/44.52 — полы на ~0.1
      //   ниже, как в правиле выше. Локальный замер 45.90/36.86/39.61/45.27
      //   завысил на 0.8 п.п. по строкам — как в #180/#223; первая версия
      //   полов ставилась по «max(main, локальный − 1.0)» и была ниже CI).
      // → 45.2/36.3/39.2/44.6 (#248: лента главной мобильного — в измерении
      //   только чистый lib/home-feed.ts (buildHomeFeed, 11 кейсов, покрыт
      //   целиком) и две строки app-dictionaries.ts. Числа по ЛОГУ CI прогона
      //   35429480181 на ветке: 45.35/36.46/39.39/44.79 — полы на ~0.1 ниже,
      //   как в правиле выше. Локальный замер 46.13/37.02/39.85/45.53
      //   завысил на 0.8 п.п. по строкам — как в #180/#223/#245).
      // → 46.1/37.4/39.8/45.5 (#259: ссылки, которые нельзя префетчить —
      //   шапка, футер и страница /subscribe впервые исполняются jsdom-тестами
      //   (site-header.tsx вместе с мобильным меню Base UI, site-footer.tsx,
      //   language-switcher.tsx, ветка AlreadySubscribed в
      //   app/subscribe/page.tsx). Локальный замер на origin/main 200cfadb +
      //   #259: 47.05/38.09/40.39/46.34 — завысил на 0.8 п.п. по строкам;
      //   полы — по логу CI прогона 35645837581: 46.26/37.53/39.93/45.6,
      //   минус 0.1, вниз до десятых).
      // → 46.5/37.6/40.1/45.8 (#266: пин версии Stripe API — lib/stripe.ts
      //   впервые исполняется тестом (страж lib/stripe-api-version.test.ts:
      //   реальный SDK, записывающий подкласс конструктора) и
      //   app/api/billing-portal/route.ts впервые под тестами целиком (четыре
      //   redirect-ветки + no-store). Локальный замер на origin/main cc1a1f61
      //   + #266: 47.35/38.27/40.56/46.60 — завысил на 0.7 п.п. по строкам.
      //   Полы — по логу CI прогона 35659514739 (дерево уже слито с main
      //   после #264/#265): 46.65/37.77/40.23/45.95, минус 0.1, вниз до
      //   десятых).
      // → 46.8/37.8/40.4/46.1 (#271: правило isInjectedScriptNoise в
      //   lib/observability.ts под тестами целиком — внедрённый скрипт,
      //   расширения, PostHog под /ingest/, линейность разбора сырого стека).
      //   Полы — по логу CI прогона 35772224297: 46.9/37.99/40.56/46.21,
      //   минус 0.1, вниз до десятых).
      // → 47.0/37.8/41.0/46.2 (#280: блок команды ушёл с /about вместе с
      //   покрытым кодом слайдера и состава; добрано тестами на поведение
      //   сборщиков JSON-LD в lib/structured-data.ts — 17 из 17 функций).
      //   Полы — по логу CI прогона 35863481243: 47.1/37.86/41.14/46.33,
      //   минус 0.1, вниз до десятых; functions держится на 37.8).
      thresholds: {
        lines: 47.0,
        functions: 37.8,
        branches: 41.0,
        statements: 46.2,
      },
    },

    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          environment: "node",
          include: [
            // `infra/` — скрипты эксплуатации (бэкапы). В покрытие они не
            // входят (см. include выше), но чистые правила вроде ретеншена
            // удаляют объекты хранилища, и проверять их обязательно.
            "{app,components,db,infra,lib,tools}/**/*.{test,spec}.{ts,tsx}",
            "proxy.test.ts",
          ],
        },
      },
      {
        // The Expo app's component tests (#247). `mobile/` stays outside the
        // pnpm workspace and outside coverage — but a component that crashes
        // a release build the moment its tab opens needs a test that renders
        // it, and the app has no runner of its own. So: the same vitest, in
        // node, with the app's own node_modules (a file under mobile/ resolves
        // `react`, `react-dom`, `@clerk/expo`… from mobile/node_modules — one
        // React, the way Metro sees it) and `react-native` pointed at the
        // react-native-web the app already ships, so a screen renders to a
        // string through react-dom/server. Native modules are vi.mock()ed per
        // test. `@/` is the app's alias (mobile/tsconfig.json), not the web's.
        extends: true,
        resolve: {
          alias: [
            {
              find: /^react-native$/,
              replacement: path.join(dirname, "mobile/node_modules/react-native-web"),
            },
            { find: /^@\/assets\//, replacement: path.join(dirname, "mobile/assets/") },
            { find: /^@\//, replacement: path.join(dirname, "mobile/src/") },
          ],
        },
        test: {
          name: "mobile",
          environment: "node",
          include: ["mobile/src/**/*.{test,spec}.{ts,tsx}"],
        },
      },
      {
        extends: true,
        plugins: [
          storybookTest({ configDir: path.join(dirname, ".storybook") }),
        ],
        test: {
          name: "storybook",
          browser: {
            enabled: true,
            headless: true,
            provider: playwright({}),
            instances: [{ browser: "chromium" }],
            expect: {
              toMatchScreenshot: {
                // Подобрано опытом, а не на глаз: при 2% перекрашенная
                // кнопка на широком холсте НЕ ловилась — её пиксели не
                // набирали порога (доска из шести кнопок прошла зелёной с
                // одной бордовой). 0.1% ловит обе доски и переживает шум
                // сглаживания.
                comparatorName: "pixelmatch",
                comparatorOptions: { allowedMismatchedPixelRatio: 0.001 },
              },
            },
          },
        },
      },
    ],
  },
});
